apiVersion: apps/v1
kind: Deployment
metadata:
  name: puck-app
  labels:
    app: puck
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: puck
  template:
    metadata:
      labels:
        app: puck
    spec:
      hostNetwork: true
      containers:
      - name: puck
        image: smehi/puck:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Define health probe
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        # Define readiness probe
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        securityContext:
            privileged: true   # Use cautiously
        volumeMounts:
          - mountPath: /dev/ttyUSB0
            name: ttyusb
          - mountPath: /dev/ttyUSB1
            name: ttyusb1
      volumes:
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        - name: ttyusb1
          hostPath:
            path: /dev/ttyUSB1
---
apiVersion: v1
kind: Service
metadata:
  name: puck-service
spec:
  selector:
    app: puck
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30671
  type: NodePort
