apiVersion: apps/v1
kind: Deployment
metadata:
  name: puck-app
  labels:
    app: puck
spec:
  replicas: 1  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: puck
  template:
    metadata:
      labels:
        app: puck
    spec:
      containers:
      - name: puck
        image: smehi/puck:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        securityContext:
            privileged: true   # Necessary for accessing devices
        volumeMounts:
          - mountPath: /dev/ttyUSB0
            name: ttyusb
      volumes:
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0  # Path to your COM port device on the host
---
apiVersion: v1
kind: Service
metadata:
  name: puck-service
spec:
  selector:
    app: puck
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30671
  type: NodePort  # Use NodePort for simplicity; consider LoadBalancer or Ingress for production

