apiVersion: apps/v1
kind: Deployment
metadata:
  name: puck-app
  labels:
    app: puck
spec:
  replicas: 1  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: puck
  template:
    metadata:
      labels:
        app: puck
    spec:
      containers:
      - name: puck
        image: smehi/puck:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: puck-service
spec:
  selector:
    app: puck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnet-ingress
spec:
  rules:
    - host: puck.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: puck-service
                port:
                  number: 80
