apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-app
  labels:
    app: aspnetcore
spec:
  replicas: 1  # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: aspnetcore
  template:
    metadata:
      labels:
        app: aspnetcore
    spec:
      containers:
      - name: puck
        image: smehi/puck:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-service
spec:
  selector:
    app: aspnetcore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use NodePort for simplicity; consider LoadBalancer or Ingress for production
